AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E9008
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Uptycs Role Parameters
        Parameters:
          - ExternalId
          - UptycsRoleName
          - UptycsAccountId
      - Label:
          default: CloudTrail Related Parameters
        Parameters:
          - CloudTrailBucket
      - Label:
          default: Permissions Boundary Info
        Parameters:
          - PermissionsBoundary
    ParameterLabels:
      UptycsSecretName:
        default: The ARN of the secret created by QuickLaunch
      CloudTrailBucket:
        default: Cloudtrail Bucket Name
      UptycsAccountId:
        default: The Uptycs Account from which the role is assumed (Only change for
          dev testing)
      UptycsRoleName:
        default: The Uptycs RoleName that will assume the role (Only change for dev
          testing)
      ExternalId:
        default: The ExternalId used by Uptycs to Assume this role
      PermissionsBoundary:
        default: The name of the permisssions boundary to apply to IAM roles


Parameters:
  CloudTrailBucket:
    Description: "Example aws-cloudtrail-logs-<accountId>-uptycs-cnap"
    Type: String
  UptycsAccountId:
    Description: Aws account id of Uptycs
    Type: String
    Default: '031552911331'
  ExternalId:
    Description: ExternalId to be used for API authentication.
    Type: String
    Default: abc123
  UptycsRoleName:
    Type: String
    Description: Name for Uptycs CSPM Reader Role
    Default: UptycsIntegrationRole
  PermissionsBoundary:
    Type: String
    Default: ''

Conditions:
  PermissionsBoundary: !Not
    - !Equals
      - !Ref 'PermissionsBoundary'
      - ''

Resources:
  UptycsIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref 'UptycsRoleName'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${UptycsAccountId}:user/AWS-API-User-PROD'
            Condition:
              StringEquals:
                sts:ExternalId: !Ref 'ExternalId'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/SecurityAudit'
  UptycsAccessPolicy:
        Type: AWS::IAM::Policy
        Properties:
          PolicyName: UptycsAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${CloudTrailBucket}/*'
                  - !Sub 'arn:${AWS::Partition}:s3:::${CloudTrailBucket}'
          Roles:
            - !Ref 'UptycsIntegrationRole'
  UptycsMemberAcctStackset:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: False
      Capabilities:
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_IAM
      Description: 'Org member account stackset'
      ManagedExecution:
        Active: True
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentCount: 20
        RegionConcurrencyType: PARALLEL
      Parameters:
        - ParameterKey: UptycsAccountId
          ParameterValue: !Ref UptycsAccountId
        - ParameterKey: UptycsRoleName
          ParameterValue: !Ref UptycsRoleName
        - ParameterKey: ExternalId
          ParameterValue: !Ref ExternalId
        - ParameterKey: PermissionsBoundary
          ParameterValue: !Ref PermissionsBoundary
      StackSetName: "UptycsIntegrationStackSet"
      PermissionModel: SERVICE_MANAGED
      TemplateURL: https://uptycs-cloud-integrations-test.s3.eu-west-1.amazonaws.com/uptycs-control-tower/templates/member_acct_template.json



