# AWS CloudFormation Template: Uptycs Service Role and StackSet
#
# Description:
# This template is designed to set up necessary roles and permissions for Uptycs
# security management across an AWS Organization. It performs two primary functions:
#
# 1. Creates an IAM role named 'UptycsIAMRole' within the master account. This role
#    is tailored for the Uptycs service, allowing it to perform actions and access
#    resources as defined by the attached policies.
#
# 2. Establishes a service-managed StackSet that contains the defined Uptycs IAM role.
#    This StackSet is configured to deploy automatically to all existing and future
#    member accounts within the organization, ensuring that Uptycs has the necessary
#    permissions across the entire AWS environment.
#
# Auto-Deployment:
# To enable automatic deployment across the organization, the StackSet is configured
# with the AutoDeployment property. This ensures that when new accounts are added to
# the organization, they will automatically receive the necessary configurations without
# manual intervention.
#
# Usage:
# Update the template with the specific permissions required by Uptycs in the IAM role
# policy definition. Before deploying this template, ensure that AWS CloudFormation
# service-linked roles and AWS Organizations are properly set up to allow for service-managed
# StackSets.
#
# Note: This template assumes that the AWS Organization and Service-Linked Role for
# CloudFormation are already in place.

AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E9008
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Uptycs Role Parameters
        Parameters:
          - ExternalId
          - UptycsRoleName
          - UptycsAccountId
      - Label:
          default: CloudTrail Related Parameters
        Parameters:
          - KMSKeyArn
          - CloudTrailBucketName
      - Label:
          default: Permissions Boundary Info
        Parameters:
          - PermissionsBoundary

    ParameterLabels:
      UptycsSecretName:
        default: The ARN of the secret created by QuickLaunch
      CloudTrailBucket:
        default: Only specify this if your Cloudtrail bucket is in THIS account
      KMSKeyArn:
        default: Add the SSE-KMS Arn if using KMS encryption.  Leave blank if using
          SSE-S3
      UptycsAccountId:
        default: The Uptycs Account from which the role is assumed (Only change for
          dev testing)
      UptycsRoleName:
        default: The Uptycs RoleName that will assume the role (Only change for dev
          testing)
      ExternalId:
        default: The ExternalId used by Uptycs to Assume this role
      PermissionsBoundary:
        default: The name of the permisssions boundary to apply to IAM roles
Parameters:
  CloudTrailBucket:
    Description: "Example aws-cloudtrail-logs-<accountId>-uptycs-cnap"
    Default: ''
    Type: String
  KMSKeyArn:
    Description: SSE-KMS Arn
    Default: ''
    Type: String
  UptycsAccountId:
    Description: Aws account id of Uptycs
    Type: String
    Default: '031552911331'
  ExternalId:
    Description: ExternalId to be used for API authentication.
    Type: String
    Default: abc123
  UptycsRoleName:
    Type: String
    Description: Name for Uptycs CSPM Reader Role
    Default: UptycsIntegrationRole
  PermissionsBoundary:
    Type: String
    Default: ''

Conditions:
  PermissionsBoundarySpecified: !Not [ !Equals [ !Ref PermissionsBoundary, "" ] ]
  CloudTrailBucketSpecified: !Not [!Equals [!Ref CloudTrailBucket, ""]]
  KMSDecryptKey: !Not [!Equals [!Ref KMSKeyArn, ""]]
Resources:
  UptycsIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref 'UptycsRoleName'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Ref UptycsAccountId
            Condition:
              StringEquals:
                sts:ExternalId: !Ref 'ExternalId'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/SecurityAudit'
  UptycsKMSDecryptPolicy:
    Type: AWS::IAM::Policy
    Condition: KMSDecryptKey
    Properties:
      PolicyName: DecryptPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DecryptLogFiles
            Action:
              - kms:Decrypt
            Effect: Allow
            Resource: !Ref 'KMSKeyArn'
      Roles:
        - !Ref 'UptycsIntegrationRole'
  UptycsAccessPolicy:
    Type: AWS::IAM::Policy
    Condition: CloudTrailBucketSpecified
    Properties:
      PolicyName: UptycsAccessPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${CloudTrailBucket}/*'
              - !Sub 'arn:${AWS::Partition}:s3:::${CloudTrailBucket}'
      Roles:
        - !Ref 'UptycsIntegrationRole'
  UptycsMemberAcctStackset:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: False
      Capabilities:
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_IAM
      Description: 'Org member account stackset'
      ManagedExecution:
        Active: True
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentCount: 20
        RegionConcurrencyType: PARALLEL
      Parameters:
        - ParameterKey: UptycsAccountId
          ParameterValue: !Ref UptycsAccountId
        - ParameterKey: UptycsRoleName
          ParameterValue: !Ref UptycsRoleName
        - ParameterKey: ExternalId
          ParameterValue: !Ref ExternalId
        - ParameterKey: PermissionsBoundary
          ParameterValue: !Ref PermissionsBoundary
      StackSetName: "UptycsIntegrationStackSet"
      PermissionModel: SERVICE_MANAGED
      TemplateURL: https://uptycs-cloud-integrations-test.s3.eu-west-1.amazonaws.com/uptycs-control-tower/templates/member_acct_template.json



